<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <!-- MSDF-Sharp for MSDF Font Atlas Generation -->
    <PackageReference Include="MSDF-Sharp" Version="1.0.2" />
    <PackageReference Include="MSDF-Sharp.Extensions" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReiStar.Maths\ReiStar.Maths.csproj" />
  </ItemGroup>

</Project>
