<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReiStar.Core\ReiStar.Core.csproj" />
    <ProjectReference Include="..\ReiStar.Graphics\ReiStar.Graphics.csproj" />
    <ProjectReference Include="..\ReiStar.Maths\ReiStar.Maths.csproj" />
  </ItemGroup>

</Project>
